name: PR Preview

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  create-update:
    name: Create EAS Update
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: "yarn"
          cache-dependency-path: yarn.lock
        env:
          SKIP_YARN_COREPACK_CHECK: "1"

      - run: corepack enable

      - name: Install dependencies
        run: yarn install

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          packager: yarn
          eas-cache: true
          patch-watchers: true

      - name: Create PR preview update
        uses: expo/expo-github-action/preview@v8
        with:
          command: eas update --channel=preview --branch=pr-${{ github.event.number }}
        env:
          EXPO_ENV: preview
